# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SMTP_FROM: ''
      SMTP_HOST: ''
      SMTP_PORT: ''
      SMTP_USER: ''
      SMTP_PASSWORD: ''
      MONGODB_URI: ''
      NEXT_PUBLIC_RUNNING_LOCAL: true
      NEXT_PUBLIC_PROTOCOL: 'http'
      NEXT_PUBLIC_PORT: 3000
      NEXT_PUBLIC_LOCAL_URL_BASE: 'localhost'
      NEXT_PUBLIC_URL_BASE: 'localhost'
      HOST_PFX: 'localhost'
      COOKIE_USER_TOKEN: ''
      COOKIE_JWT_INFO: ''
      JWT_SECRET_KEY: ''
      JWT_ALGORITHM: ''
      JWT_EXP_MINUTES: ''
      LOGFARE_API_KEY: ''
      LOGFARE_API_URL: ''

    strategy:
      matrix:
        node-version: [18.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./my-portfolio

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './my-portfolio/package-lock.json'
    - name: Install dependencies
      run: npm install
    - run: npm run build --if-present
    - run: npm test
    - run: npm run test:ci
